id: P001701
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W1KG14137
  title: གཏམ་མཛོད་མེས་པོའི་ཞལ་རྒྱུན།
  author: ''
  volumes:
    a1f5892ff29048a1bc1fc08ff4611604:
      image_group_id: I1KG14330
      title: ''
      volume_number: 1
      total_pages: 388
      base_file: v001.txt
